site_name: AFMussap Tech Shopping List
pages:
    - Overview: 'index.md'
    - Installation.md: 'installation.md'
    - Features:
        - 'Custom Lists': 'custom_lists.md'
        - 'Items': 'items.md'
        - 'General information': 'general.md'
theme: readthedocs
google_analytics: ['UA-45971598-3', 'auto']
