site_name: AFMussap Tech Shopping List
pages:
    - Overview: 'index.md'
    - Installation: 'installation.md'
    - Features:
        - 'Custom Lists': 'custom_lists.md'
        - 'Items': 'items.md'
        - 'Sum': 'total_amount.md'
        - 'Menu options': 'menu_options.md'
theme: readthedocs
google_analytics: ['UA-45971598-3', 'auto']
